export enum NamingType {
  GITHUB_REPO = 'githubRepo',
  CAMEL_CASE = 'camelCase',
  SNAKE_CASE = 'snakeCase',
  GIT_BRANCH = 'gitBranch',
}

const vocabularyMap: Record<string, string> = {
  用户: 'user',
  使用者: 'user',
  管理员: 'admin',
  订单: 'order',
  商品: 'product',
  产品: 'product',
  列表: 'list',
  详情: 'detail',
  信息: 'info',
  数据: 'data',
  配置: 'config',
  设置: 'setting',
  选项: 'option',
  参数: 'param',
  类型: 'type',
  状态: 'status',
  状态码: 'statusCode',
  错误: 'error',
  警告: 'warning',
  成功: 'success',
  失败: 'fail',
  结果: 'result',
  响应: 'response',
  请求: 'request',
  查询: 'query',
  搜索: 'search',
  查找: 'find',
  创建: 'create',
  添加: 'add',
  新增: 'add',
  更新: 'update',
  修改: 'update',
  编辑: 'edit',
  删除: 'delete',
  移除: 'remove',
  获取: 'get',
  读取: 'read',
  保存: 'save',
  存储: 'store',
  加载: 'load',
  初始化: 'init',
  初始化: 'initialize',
  销毁: 'destroy',
  关闭: 'close',
  打开: 'open',
  启用: 'enable',
  禁用: 'disable',
  激活: 'active',
  停用: 'inactive',
  有效: 'valid',
  无效: 'invalid',
  验证: 'validate',
  校验: 'check',
  检查: 'check',
  测试: 'test',
  调试: 'debug',
  日志: 'log',
  记录: 'record',
  历史: 'history',
  时间: 'time',
  日期: 'date',
  日期时间: 'datetime',
  时间戳: 'timestamp',
  时长: 'duration',
  间隔: 'interval',
  超时: 'timeout',
  延迟: 'delay',
  倒计时: 'countdown',
  缓存: 'cache',
  内存: 'memory',
  存储: 'storage',
  数据库: 'database',
  连接: 'connection',
  会话: 'session',
  令牌: 'token',
  密钥: 'key',
  密码: 'password',
  账号: 'account',
  邮箱: 'email',
  手机: 'phone',
  手机号: 'mobile',
  名称: 'name',
  标题: 'title',
  描述: 'description',
  简介: 'intro',
  内容: 'content',
  正文: 'body',
  头部: 'header',
  底部: 'footer',
  侧边栏: 'sidebar',
  菜单: 'menu',
  导航: 'nav',
  链接: 'link',
  按钮: 'button',
  输入框: 'input',
  表单: 'form',
  表格: 'table',
  卡片: 'card',
  弹窗: 'modal',
  对话框: 'dialog',
  提示: 'tooltip',
  通知: 'notification',
  消息: 'message',
  通知: 'notice',
  提醒: 'reminder',
  标签: 'tag',
  徽章: 'badge',
  图标: 'icon',
  图片: 'image',
  图片: 'img',
  视频: 'video',
  音频: 'audio',
  文件: 'file',
  文件夹: 'folder',
  目录: 'directory',
  路径: 'path',
  地址: 'address',
  位置: 'location',
  坐标: 'coordinate',
  大小: 'size',
  宽度: 'width',
  高度: 'height',
  长度: 'length',
  数量: 'count',
  总数: 'total',
  数量: 'amount',
  价格: 'price',
  金额: 'amount',
  余额: 'balance',
  积分: 'point',
  等级: 'level',
  权限: 'permission',
  角色: 'role',
  部门: 'department',
  组织: 'organization',
  公司: 'company',
  团队: 'team',
  项目: 'project',
  任务: 'task',
  工作: 'job',
  作业: 'work',
  流程: 'process',
  步骤: 'step',
  阶段: 'phase',
  周期: 'cycle',
  版本: 'version',
  修订: 'revision',
  发布: 'release',
  构建: 'build',
  部署: 'deploy',
  环境: 'environment',
  开发: 'dev',
  测试: 'test',
  预发布: 'staging',
  生产: 'prod',
  线上: 'online',
  线下: 'offline',
  本地: 'local',
  远程: 'remote',
  全局: 'global',
  局部: 'local',
  公共: 'public',
  私有: 'private',
  内部: 'internal',
  外部: 'external',
  静态: 'static',
  动态: 'dynamic',
  常量: 'constant',
  变量: 'variable',
  临时: 'temp',
  临时: 'temporary',
  最终: 'final',
  初始: 'initial',
  默认: 'default',
  当前: 'current',
  上一个: 'prev',
  下一个: 'next',
  第一个: 'first',
  最后一个: 'last',
  全部: 'all',
  部分: 'part',
  一些: 'some',
  任何: 'any',
  没有: 'none',
  空: 'empty',
  空: 'null',
  未定义: 'undefined',
  未知: 'unknown',
  新的: 'new',
  旧的: 'old',
  大: 'large',
  中: 'medium',
  小: 'small',
  最大: 'max',
  最小: 'min',
  首页: 'home',
  登录: 'login',
  登出: 'logout',
  注册: 'register',
  忘记密码: 'forgotPassword',
  重置密码: 'resetPassword',
  个人中心: 'profile',
  设置: 'settings',
  关于: 'about',
  联系: 'contact',
  帮助: 'help',
  文档: 'docs',
  文档: 'document',
  教程: 'tutorial',
  指南: 'guide',
  示例: 'example',
  演示: 'demo',
  沙箱: 'sandbox',
  控制台: 'console',
  仪表盘: 'dashboard',
  面板: 'panel',
  工作台: 'workspace',
  编辑器: 'editor',
  预览: 'preview',
  导出: 'export',
  导入: 'import',
  下载: 'download',
  上传: 'upload',
  分享: 'share',
  复制: 'copy',
  剪切: 'cut',
  粘贴: 'paste',
  撤销: 'undo',
  重做: 'redo',
  刷新: 'refresh',
  重新加载: 'reload',
  清空: 'clear',
  重置: 'reset',
  提交: 'submit',
  确认: 'confirm',
  取消: 'cancel',
  确定: 'ok',
  是: 'yes',
  否: 'no',
  同意: 'agree',
  拒绝: 'decline',
  接受: 'accept',
  拒绝: 'reject',
  批准: 'approve',
  拒绝: 'deny',
  通过: 'pass',
  失败: 'fail',
  完成: 'complete',
  完成: 'done',
  结束: 'finish',
  开始: 'start',
  开始: 'begin',
  暂停: 'pause',
  继续: 'resume',
  停止: 'stop',
  终止: 'terminate',
  退出: 'exit',
  返回: 'back',
  返回: 'return',
  前进: 'forward',
  后退: 'back',
  上一页: 'prevPage',
  下一页: 'nextPage',
  跳转: 'jump',
  跳转: 'goTo',
  滚动: 'scroll',
  滑动: 'swipe',
  拖拽: 'drag',
  放下: 'drop',
  选择: 'select',
  选中: 'selected',
  取消选中: 'unselected',
  高亮: 'highlight',
  焦点: 'focus',
  悬停: 'hover',
  点击: 'click',
  双击: 'dblClick',
  右键: 'rightClick',
  键盘: 'keyboard',
  鼠标: 'mouse',
  触摸: 'touch',
  手势: 'gesture',
  动画: 'animation',
  过渡: 'transition',
  效果: 'effect',
  样式: 'style',
  主题: 'theme',
  皮肤: 'skin',
  颜色: 'color',
  背景: 'background',
  前景: 'foreground',
  边框: 'border',
  边距: 'margin',
  内边距: 'padding',
  间距: 'spacing',
  对齐: 'align',
  布局: 'layout',
  网格: 'grid',
  弹性: 'flex',
  响应式: 'responsive',
  自适应: 'adaptive',
  移动端: 'mobile',
  桌面端: 'desktop',
  平板: 'tablet',
  横屏: 'landscape',
  竖屏: 'portrait',
  语言: 'language',
  国际化: 'i18n',
  本地化: 'l10n',
  翻译: 'translate',
  单位: 'unit',
  格式: 'format',
  编码: 'encode',
  解码: 'decode',
  压缩: 'compress',
  解压: 'decompress',
  加密: 'encrypt',
  解密: 'decrypt',
  签名: 'sign',
  验签: 'verify',
  哈希: 'hash',
  摘要: 'digest',
  算法: 'algorithm',
  规则: 'rule',
  策略: 'strategy',
  模式: 'pattern',
  模板: 'template',
  组件: 'component',
  模块: 'module',
  插件: 'plugin',
  扩展: 'extension',
  工具: 'util',
  工具: 'helper',
  服务: 'service',
  控制器: 'controller',
  路由: 'router',
  中间件: 'middleware',
  过滤器: 'filter',
  拦截器: 'interceptor',
  处理器: 'handler',
  管理器: 'manager',
  工厂: 'factory',
  单例: 'singleton',
  实例: 'instance',
  对象: 'object',
  数组: 'array',
  列表: 'list',
  集合: 'set',
  映射: 'map',
  字典: 'dictionary',
  枚举: 'enum',
  常量: 'const',
  变量: 'let',
  函数: 'function',
  方法: 'method',
  类: 'class',
  接口: 'interface',
  类型: 'type',
  泛型: 'generic',
  异步: 'async',
  同步: 'sync',
  并行: 'parallel',
  串行: 'serial',
  并发: 'concurrent',
  线程: 'thread',
  进程: 'process',
  协程: 'coroutine',
  任务: 'task',
  队列: 'queue',
  栈: 'stack',
  堆: 'heap',
  树: 'tree',
  图: 'graph',
  链表: 'linkedList',
  节点: 'node',
  叶子: 'leaf',
  根: 'root',
  父: 'parent',
  子: 'child',
  兄弟: 'sibling',
  祖先: 'ancestor',
  后代: 'descendant',
  深度: 'depth',
  层级: 'level',
  路径: 'path',
  路由: 'route',
  端点: 'endpoint',
  接口: 'api',
  接口: 'interface',
  服务: 'service',
  微服务: 'microservice',
  网关: 'gateway',
  代理: 'proxy',
  负载均衡: 'loadBalance',
  熔断: 'circuitBreak',
  降级: 'degrade',
  限流: 'rateLimit',
  缓存: 'cache',
  持久化: 'persist',
  事务: 'transaction',
  提交: 'commit',
  回滚: 'rollback',
  锁: 'lock',
  死锁: 'deadlock',
  乐观锁: 'optimisticLock',
  悲观锁: 'pessimisticLock',
  原子: 'atomic',
  一致性: 'consistency',
  可用性: 'availability',
  分区容错: 'partitionTolerance',
  分布式: 'distributed',
  集群: 'cluster',
  节点: 'node',
  副本: 'replica',
  主从: 'masterSlave',
  主: 'master',
  从: 'slave',
  选举: 'election',
  共识: 'consensus',
  协议: 'protocol',
  规范: 'spec',
  标准: 'standard',
  约定: 'convention',
  配置: 'config',
  环境变量: 'env',
  命令行: 'cli',
  参数: 'args',
  选项: 'options',
  标志: 'flag',
  输出: 'output',
  输入: 'input',
  标准输入: 'stdin',
  标准输出: 'stdout',
  标准错误: 'stderr',
  管道: 'pipe',
  重定向: 'redirect',
  脚本: 'script',
  命令: 'command',
  任务: 'job',
  定时任务: 'cron',
  调度: 'schedule',
  执行: 'execute',
  运行: 'run',
  启动: 'start',
  停止: 'stop',
  重启: 'restart',
  重载: 'reload',
  健康检查: 'healthCheck',
  监控: 'monitor',
  告警: 'alert',
  指标: 'metric',
  追踪: 'trace',
  日志: 'log',
  审计: 'audit',
  报告: 'report',
  统计: 'stats',
  分析: 'analytics',
  报表: 'report',
  图表: 'chart',
  图形: 'graph',
  画布: 'canvas',
  SVG: 'svg',
  矢量图: 'vector',
  位图: 'bitmap',
  像素: 'pixel',
  分辨率: 'resolution',
  密度: 'density',
  比例: 'ratio',
  缩放: 'scale',
  旋转: 'rotate',
  翻转: 'flip',
  裁剪: 'crop',
  滤镜: 'filter',
  水印: 'watermark',
  缩略图: 'thumbnail',
  原图: 'original',
  压缩: 'compress',
  质量: 'quality',
  格式: 'format',
  类型: 'mimeType',
  扩展名: 'extension',
  文件名: 'filename',
  大小: 'size',
  字节: 'byte',
  千字节: 'kb',
  兆字节: 'mb',
  千兆字节: 'gb',
  流: 'stream',
  缓冲区: 'buffer',
  块: 'chunk',
  片段: 'segment',
  偏移: 'offset',
  位置: 'position',
  指针: 'pointer',
  索引: 'index',
  键: 'key',
  值: 'value',
  键值对: 'keyValue',
  条目: 'entry',
  记录: 'record',
  行: 'row',
  列: 'column',
  字段: 'field',
  属性: 'property',
  特性: 'attribute',
  元素: 'element',
  项: 'item',
  项目: 'item',
  分组: 'group',
  分类: 'category',
  类型: 'kind',
  种类: 'type',
  标签: 'label',
  标记: 'flag',
  标识: 'id',
  标识符: 'identifier',
  别名: 'alias',
  代号: 'code',
  编号: 'number',
  序号: 'serial',
  页码: 'page',
  每页数量: 'pageSize',
  总页数: 'totalPages',
  总数: 'total',
  偏移: 'offset',
  限制: 'limit',
  排序: 'sort',
  升序: 'asc',
  降序: 'desc',
  过滤: 'filter',
  条件: 'condition',
  表达式: 'expression',
  语句: 'statement',
  运算符: 'operator',
  操作数: 'operand',
  逻辑: 'logic',
  算术: 'arithmetic',
  比较: 'compare',
  等于: 'equal',
  不等于: 'notEqual',
  大于: 'greaterThan',
  小于: 'lessThan',
  大于等于: 'greaterThanOrEqual',
  小于等于: 'lessThanOrEqual',
  包含: 'contains',
  不包含: 'notContains',
  存在: 'exists',
  不存在: 'notExists',
  为空: 'isNull',
  不为空: 'isNotNull',
  为空: 'isEmpty',
  不为空: 'isNotEmpty',
  真: 'true',
  假: 'false',
  是: 'true',
  否: 'false',
  与: 'and',
  或: 'or',
  非: 'not',
  如果: 'if',
  否则: 'else',
  否则如果: 'elseIf',
  开关: 'switch',
  情况: 'case',
  默认: 'default',
  循环: 'loop',
  对于: 'for',
  当: 'while',
  做: 'do',
  遍历: 'forEach',
  映射: 'map',
  过滤: 'filter',
  归约: 'reduce',
  累加: 'accumulate',
  聚合: 'aggregate',
  分组: 'group',
  排序: 'orderBy',
  去重: 'distinct',
  分页: 'paginate',
  切片: 'slice',
  截取: 'substring',
  分割: 'split',
  连接: 'join',
  合并: 'merge',
  拼接: 'concat',
  替换: 'replace',
  匹配: 'match',
  搜索: 'search',
  查找: 'find',
  查找所有: 'findAll',
  第一个: 'first',
  最后一个: 'last',
  索引: 'indexOf',
  最后索引: 'lastIndexOf',
  包含: 'includes',
  开始于: 'startsWith',
  结束于: 'endsWith',
  大写: 'toUpperCase',
  小写: 'toLowerCase',
  首字母大写: 'capitalize',
  驼峰: 'camelCase',
  蛇形: 'snakeCase',
  短横线: 'kebabCase',
  帕斯卡: 'pascalCase',
  常量: 'constantCase',
  修剪: 'trim',
  左修剪: 'trimLeft',
  右修剪: 'trimRight',
  填充: 'pad',
  左填充: 'padLeft',
  右填充: 'padRight',
  重复: 'repeat',
  反转: 'reverse',
  随机: 'random',
  唯一: 'unique',
  生成: 'generate',
  创建: 'create',
  实例化: 'instantiate',
  初始化: 'initialize',
  构造: 'construct',
  销毁: 'destroy',
  释放: 'release',
  清理: 'cleanup',
  回收: 'collect',
  垃圾回收: 'garbageCollect',
  引用: 'reference',
  指针: 'pointer',
  地址: 'address',
  值: 'value',
  类型: 'type',
  原型: 'prototype',
  构造函数: 'constructor',
  析构函数: 'destructor',
  静态: 'static',
  实例: 'instance',
  继承: 'inherit',
  扩展: 'extend',
  实现: 'implement',
  抽象: 'abstract',
  接口: 'interface',
  混入: 'mixin',
  装饰器: 'decorator',
  注解: 'annotation',
  泛型: 'generic',
  重载: 'overload',
  重写: 'override',
  多态: 'polymorphism',
  封装: 'encapsulation',
  抽象: 'abstraction',
  继承: 'inheritance',
  组合: 'composition',
  聚合: 'aggregation',
  依赖: 'dependency',
  耦合: 'coupling',
  内聚: 'cohesion',
  单一职责: 'singleResponsibility',
  开闭: 'openClosed',
  里氏替换: 'liskovSubstitution',
  接口隔离: 'interfaceSegregation',
  依赖倒置: 'dependencyInversion',
  控制反转: 'inversionOfControl',
  依赖注入: 'dependencyInjection',
  工厂: 'factory',
  抽象工厂: 'abstractFactory',
  建造者: 'builder',
  单例: 'singleton',
  原型: 'prototype',
  适配器: 'adapter',
  桥接: 'bridge',
  组合: 'composite',
  装饰: 'decorator',
  外观: 'facade',
  享元: 'flyweight',
  代理: 'proxy',
  责任链: 'chainOfResponsibility',
  命令: 'command',
  解释器: 'interpreter',
  迭代器: 'iterator',
  中介者: 'mediator',
  备忘录: 'memento',
  观察者: 'observer',
  状态: 'state',
  策略: 'strategy',
  模板方法: 'templateMethod',
  访问者: 'visitor',
  新特性: 'feature',
  修复: 'fix',
  改进: 'improve',
  优化: 'optimize',
  重构: 'refactor',
  测试: 'test',
  文档: 'docs',
  样式: 'style',
   chore: 'chore',
  回退: 'revert',
  发布: 'release',
  性能: 'performance',
  安全: 'security',
  可用性: 'usability',
  可维护性: 'maintainability',
  可扩展性: 'scalability',
  可移植性: 'portability',
  兼容性: 'compatibility',
  可靠性: 'reliability',
  稳定性: 'stability',
  一致性: 'consistency',
  正确性: 'correctness',
  完整性: 'integrity',
  准确性: 'accuracy',
  精度: 'precision',
  效率: 'efficiency',
  响应时间: 'responseTime',
  吞吐量: 'throughput',
  并发数: 'concurrency',
  延迟: 'latency',
  带宽: 'bandwidth',
  容量: 'capacity',
  可用性: 'availability',
  容错: 'faultTolerance',
  恢复: 'recovery',
  备份: 'backup',
  还原: 'restore',
  归档: 'archive',
  清理: 'cleanup',
  过期: 'expire',
  失效: 'invalidate',
  刷新: 'refresh',
  更新: 'update',
  同步: 'sync',
  异步: 'async',
  并行: 'parallel',
  串行: 'serial',
  批量: 'batch',
  增量: 'incremental',
  全量: 'full',
  部分: 'partial',
  完整: 'complete',
  最小: 'min',
  最大: 'max',
  平均: 'avg',
  总和: 'sum',
  计数: 'count',
  百分比: 'percent',
  比例: 'ratio',
  频率: 'frequency',
  速度: 'speed',
  速率: 'rate',
  间隔: 'interval',
  周期: 'period',
  持续时间: 'duration',
  超时: 'timeout',
  截止日期: 'deadline',
  到期: 'expire',
  开始: 'start',
  结束: 'end',
  开始时间: 'startTime',
  结束时间: 'endTime',
  创建时间: 'createdAt',
  更新时间: 'updatedAt',
  删除时间: 'deletedAt',
  修改时间: 'modifiedAt',
  访问时间: 'accessedAt',
  过期时间: 'expiredAt',
  有效期: 'validPeriod',
  生命周期: 'lifecycle',
  状态: 'status',
  进度: 'progress',
  百分比: 'percent',
  完成度: 'completion',
  处理中: 'processing',
  等待中: 'waiting',
  待处理: 'pending',
  排队中: 'queued',
  运行中: 'running',
  执行中: 'executing',
  已启动: 'started',
  已停止: 'stopped',
  已暂停: 'paused',
  已恢复: 'resumed',
  已取消: 'cancelled',
  已中止: 'aborted',
  已失败: 'failed',
  已成功: 'succeeded',
  已完成: 'completed',
  已结束: 'ended',
  已过期: 'expired',
  已失效: 'invalidated',
  已删除: 'deleted',
  已归档: 'archived',
  已备份: 'backedUp',
  已还原: 'restored',
  已锁定: 'locked',
  已解锁: 'unlocked',
  已冻结: 'frozen',
  已解冻: 'thawed',
  已激活: 'activated',
  已停用: 'deactivated',
  已启用: 'enabled',
  已禁用: 'disabled',
  已发布: 'published',
  已撤回: 'withdrawn',
  已提交: 'committed',
  已回滚: 'rolledBack',
  已确认: 'confirmed',
  已拒绝: 'rejected',
  已批准: 'approved',
  已拒绝: 'denied',
  已通过: 'passed',
  未通过: 'failed',
  待审核: 'pendingReview',
  已审核: 'reviewed',
  待确认: 'pendingConfirmation',
  已确认: 'confirmed',
  待支付: 'pendingPayment',
  已支付: 'paid',
  已退款: 'refunded',
  已取消: 'cancelled',
  已关闭: 'closed',
  已打开: 'open',
  已解决: 'resolved',
  未解决: 'unresolved',
  已修复: 'fixed',
  未修复: 'unfixed',
  已知: 'known',
  未知: 'unknown',
  新的: 'new',
  旧的: 'old',
  活动: 'active',
  非活动: 'inactive',
  在线: 'online',
  离线: 'offline',
  空闲: 'idle',
  忙碌: 'busy',
  可用: 'available',
  不可用: 'unavailable',
  已满: 'full',
  未满: 'notFull',
  为空: 'empty',
  不为空: 'notEmpty',
  '为 null': 'isNull',
  '不为 null': 'isNotNull',
  为真: 'isTrue',
  为假: 'isFalse',
  相等: 'equals',
  不等: 'notEquals',
  相同: 'same',
  不同: 'different',
  大于: 'greater',
  小于: 'less',
  大于等于: 'greaterOrEqual',
  小于等于: 'lessOrEqual',
  包含: 'includes',
  不包含: 'excludes',
  存在: 'exists',
  不存在: 'notExists',
  匹配: 'matches',
  不匹配: 'notMatches',
  '以...开头': 'startsWith',
  '以...结尾': 'endsWith',
  包含于: 'containedIn',
  不包含于: 'notContainedIn',
  '介于...之间': 'between',
  '不介于...之间': 'notBetween',
  相似: 'like',
  不相似: 'notLike',
  正则匹配: 'regexp',
  正则不匹配: 'notRegexp',
}

function translateWords(input: string): string[] {
  const words: string[] = []
  let remaining = input

  while (remaining.length > 0) {
    let matched = false

    for (const [chinese, english] of Object.entries(vocabularyMap)) {
      if (remaining.startsWith(chinese)) {
        words.push(english)
        remaining = remaining.slice(chinese.length)
        matched = true
        break
      }
    }

    if (!matched) {
      const char = remaining[0]
      if (/[a-zA-Z0-9]/.test(char)) {
        let alphaNum = ''
        let i = 0
        while (i < remaining.length && /[a-zA-Z0-9]/.test(remaining[i])) {
          alphaNum += remaining[i]
          i++
        }
        words.push(alphaNum)
        remaining = remaining.slice(i)
      } else {
        remaining = remaining.slice(1)
      }
    }
  }

  return words
}

function toCamelCase(words: string[]): string {
  if (words.length === 0) return ''

  return words
    .map((word, index) => {
      const lowerWord = word.toLowerCase()
      if (index === 0) {
        return lowerWord
      }
      return lowerWord.charAt(0).toUpperCase() + lowerWord.slice(1)
    })
    .join('')
}

function toSnakeCase(words: string[]): string {
  return words.map((word) => word.toLowerCase()).join('_')
}

function toKebabCase(words: string[]): string {
  return words.map((word) => word.toLowerCase()).join('-')
}

function toPascalCase(words: string[]): string {
  return words
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
}

function toConstantCase(words: string[]): string {
  return words.map((word) => word.toUpperCase()).join('_')
}

export function generateName(input: string, type: NamingType): string {
  const words = translateWords(input)

  if (words.length === 0) {
    return ''
  }

  switch (type) {
    case NamingType.GITHUB_REPO:
      return toKebabCase(words)
    case NamingType.CAMEL_CASE:
      return toCamelCase(words)
    case NamingType.SNAKE_CASE:
      return toSnakeCase(words)
    case NamingType.GIT_BRANCH: {
      const prefixMap: Record<string, string> = {
        新特性: 'feature',
        功能: 'feature',
        新增: 'feature',
        修复: 'fix',
        bug: 'fix',
        错误: 'fix',
        问题: 'fix',
        改进: 'improve',
        优化: 'optimize',
        性能: 'perf',
        文档: 'docs',
        样式: 'style',
        重构: 'refactor',
        测试: 'test',
        构建: 'build',
        部署: 'deploy',
        发布: 'release',
        安全: 'security',
        依赖: 'deps',
        回退: 'revert',
      }

      const firstWord = words[0].toLowerCase()
      let prefix = 'feature'

      for (const [keyword, p] of Object.entries(prefixMap)) {
        if (firstWord.includes(keyword) || words.some(w => w.toLowerCase().includes(keyword))) {
          prefix = p
          break
        }
      }

      const remainingWords = words.filter((w) => {
        const lowerW = w.toLowerCase()
        return !Object.keys(prefixMap).some((k) => lowerW.includes(k))
      })

      if (remainingWords.length === 0) {
        return `${prefix}/default`
      }

      return `${prefix}/${toKebabCase(remainingWords)}`
    }
    default:
      return toCamelCase(words)
  }
}

export const namingTypeLabels: Record<NamingType, string> = {
  [NamingType.GITHUB_REPO]: 'GitHub 仓库名',
  [NamingType.CAMEL_CASE]: 'camelCase 字段名',
  [NamingType.SNAKE_CASE]: 'snake_case 字段名',
  [NamingType.GIT_BRANCH]: 'Git 分支名',
}
